[package]
name = "sha256_sudoku"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
common = { path = "../common" }
chacha20 = "0.9.1"
