[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", rev = "3ab63a6", optional = true }

[features]
default = []
secp256k1 = ["dep:crypto-bigint"]
