[package]
name = "dlog_secp256k1_sha256"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
common = { path = "../common", features = ["secp256k1"] }
